project_name: cloud-platform-po-linter
before:
  hooks:
    - go mod download
builds:
  - env:
    - CGO_ENABLED=0
    main: ./cloud-platform-po-linter.go
    binary: cloud-platform-po-linter
    goos:
      - linux
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    ldflags:
      - -s -w
changelog:
  sort: asc
  filters:
    exclude:
      - Merge pull request
      - Merge branch
      - go mod tidy
dockers:
- 
  image_templates: 
  - "ministryofjustice/cloud-platform-po-linter:{{ .Tag}}"
  - "ministryofjustice/cloud-platform-po-linter:{{ .Version}}"
  use: buildx
  dockerfile: Dockerfile